### ISSUE TITLE
General Comments

### ISSUE THREAD

**Issue by yoadsn** [stoffern/graphql-compose-dataloader#1]
@stoffern Thank you for your work! Great Progress!

After reviewing it a bit, here are some things to note:
**singleContinous**
Some of the caching strategy is implemented using the `singleContinous` module. The description of the module is "This class makes shure functions with params only run once" But I think from the code it does something different.
I think it's making sure that data is cleared from the cache a certain amount of time after the first call is made. (As an aside this could be implemented using a debouncer, maybe use the one in lodash to make life easier).

Anyway, clearing the cache is a job of the cache and DataLoader allows implementing custom "stores" to handle cache logic. The "options" object of the DataLoader constructor accepts a `cacheMap` property that is a Map like instance of an object where this logic should go.

Regardless, DataLoader is not supposed to do any caching outside a single request, and so when composing it, we should attach it to the context and not reuse it for other requests. For that, there are other types of application cache that can be used. Then, caching expiration logic has a place..

**Hash of Requests**
This is a nice trick, I wonder if it doesn't cause the DataLoader to hit the cache too little... say I ask the same entity (same ID from findByID) but want different fields.. in that case I think that DataLoader would load twice. So currently it's mostly caching the data of the exact same requests, kinda like memoization of the GQL api - right?

**Comment by stoffern** [comment]
#### singleContinous
The description may have been a bit misleading.. sorry about that.
The useage of it is as follows. By default if you create a DataLoader(DL) cache when creating the TC object there will be a persistent cache, and it will not clear it after any of the requests.
This is why whenever a DL.load() request is sendt it will also send a async DL.clear() request that will be executed after amout of exipration time.
And having 400 loads in one request (this will fire 400 .clear() requests aswell)
this is where singleContinous comes in.. it skips every duplicates and keeps track so that there will only be one clear request pr unique load().


#### Hash of requests
Well by default `graphql-compose-dataloader` deactivated projection and retrieves full documents.
If removing the projection is true, it willl remove the projection before the hashing. 
This will cache the document and if you request other fields it will return the same cached document.

If projection is set to false, then it is true that it will have minimal cache.
THis beeing said, i have tested mongoose connections and queries, (every request is between 20-30ms depending on document size, cache is 2-3 ms) and if you remove projection vs not doing it it will in almost all cases give huge speed wins. The document have to be really big in order to be faster when projection is on.

**Comment by stoffern** [comment]
and btw, debouncer will not work as it is async tasks that execute at the same time
